hmcts/slack-help-bot

- infrastructure/data.tf
- infrastructure/identity.tf
> Tf fixes, extra param

- .dockerignore
- app.js
- src/service/persistence.js
Fixes #14
Also: 
* Speed up docker build
* Add error handling - Jira is unstable atm and I was getting some angry messages about unhandled errors by node.js
> Resolve display names to Jira in comments

- app.js
Relates to https://github.com/hmcts/slack-help-bot/issues/18
> Add try catch blocks to all functions

- app.js
- src/messages.js
- src/service/persistence.js
> Add MI information to labels

- src/service/persistence.functional.test.js
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Add Labels to persistence.functional.test.js

- config/custom-environment-variables.yaml
- config/default.yaml
- env.template.txt
- src/service/persistence.js
- src/setupSecrets.js
Hopefully this doesn't get locked when new users come on and use the
wrong password
> Switch to API token

- src/messages.js
https://tools.hmcts.net/jira/browse/DTSPO-3996
Add Access Management to the team list
```
[ ] Yes
[X] No
```
> Add Access Management

- src/messages.js
https://tools.hmcts.net/jira/browse/DTSPO-3996
Add AM identifier
```
[ ] Yes
[X] No
```
> Add am identifier

- .github/workflows/main.yml
> Sortable Image tagging for flux v2

- package-lock.json
- package.json
> Properties-volume - dependency updates

- app.js
- config/custom-environment-variables.yaml
- config/default.yaml
- env.template.txt
- package-lock.json
- package.json
- src/setupSecrets.js
> DTSPO-6714 Add App Insights Reporting

- .github/workflows/main.yml
> Update docker image tagging

- .github/workflows/main.yml
> Fix typo in main.yml

- app.js
> Fix bug in ticket resolution method

- app.js
- src/service/persistence.js
> Improved logging in case posting help request to Jira fails.

- src/service/persistence.js
> Additional logging when creating jira issue

- src/messages.js
Implement basic range checks for the 'description' and 'analysis' fields so messages do not exceed the API's character limit.
```
[ ] Yes
[ ] No
```
> Add range check to help request details

- .github/CODEOWNERS
https://tools.hmcts.net/jira/browse/DTSPO-8837
Fix codeowners file
```
[ ] Yes
[x] No
```
> DTSPO-8837 - Fix codeowners file

- infrastructure/identity.tf
- pipeline/templates/terraform/terraform.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9049
Add publishPlanResults to Azure DevOps pipeline
```
[ ] Yes
[x] No
```
> DTSPO-9049 - Add publishPlanResults

- infrastructure/provider.tf
- pipeline/azure-pipelines.yml
Bump TF version used in pipeline to use newer TF required_version in code
```
[ ] Yes
[x] No
```
> buump tf version in ci to 1.3.9

- src/messages.js
None
Update resolution drop down menu list to add a new value as requested by Praveen. This has been tested with no issues. 
```
[ ] Yes
[ X] No
```
> Update resolution drop down menu list

- .github/renovate.json
- renovate.json
Enable auto-merge for renovate PRs
```
[ ] Yes
[x] No
```
> DTSPO-11734 - renovate - enable automerge

- package-lock.json
Reverts hmcts/slack-help-bot#288
Slack bot is in a crash loop. Checking to see if this is the culprit
> Revert "Update dependency applicationinsights to v2.9.2"

- app.js
- src/service/persistence.js
- Adds new `removeAutowithdrawLabel` function
- Adds call to function when help request is started
> Remove auto-withdraw label when re-opening issue

- components/infrastructure/ai-cosmos.tf
- components/infrastructure/ai-permissions.tf
> Add cosmos db account and AI Services permissions

- src/service/persistence.js
Noticed in logs:
```
Querying username failed: TypeError: Cannot read properties of undefined (reading 'name')
```
> Handle email not being found in Jira

- src/slackHandlers/appMessaged.js
Not sure how you can do this but I noticed it in the logs, easy fix to prevent it
> Fix undefined on bot message

- README.md
refresh bot intro
I thought it would be good to document everything the bot can do.
> Document bot features

- README.md
- config/default.yaml
- src/scripts/loadAllRequestsToCosmos.js
- src/service/cosmos.js
- src/service/persistence.js
- src/slackHandlers/documentHelpRequest.js
- src/slackHandlers/submitHelpRequest.js
Fixes https://github.com/hmcts/slack-help-bot/issues/381
> Add syncing of new and updated requests to Cosmos

- src/service/persistence.js
- src/slackHandlers/appMention.js
Fixes https://github.com/hmcts/slack-help-bot/issues/73
Fixes https://github.com/hmcts/slack-help-bot/issues/66
> Improve validation and UX of duplicating issues

- components/infrastructure/ai-search-cosmos-datasource.tf
- components/infrastructure/ai-search-help-request-index.tf
- components/infrastructure/ai-search-help-request-indexer.tf
- components/infrastructure/ai-search-hmcts-way-index.tf
- components/infrastructure/ai-search-hmcts-way-indexer.tf
- components/infrastructure/ai-search-storage-account-datasource.tf
- components/infrastructure/ai-storage.tf
https://github.com/hmcts/slack-help-bot/issues/382
Add infra for knowledge store searching , see code in https://github.com/hmcts/slack-help-bot/pull/394
Will probably add a module when doing the crime bit
> Create infra for knowledge store ingestion

- components/infrastructure/ai-search-hmcts-way-index.tf
- components/infrastructure/ai-search-hmcts-way-indexer.tf
https://github.com/hmcts/slack-help-bot/issues/382
> Tweak index

- components/infrastructure/ai-search-hmcts-way-index.tf
content field went past the size limit
> Tweak index again

- components/infrastructure/ai-search-help-request-index.tf
https://tools.hmcts.net/jira/browse/DTSPO-18481
Allow filtering by if crime or not
> DTSPO-18481 Add area to index

- app.js
- package-lock.json
- package.json
- src/messages/helpFormMain.js
- src/messages/util.js
- src/service/searchKnowledgeStore.js
- src/slackHandlers/submitHelpRequest.js
- src/slackHandlers/submitInitialHelpRequest.js
- src/slackHandlers/utils/aiCache.js
- src/slackHandlers/utils/hashString.js
- src/slackHandlers/utils/hashString.test.js
- src/slackHandlers/utils/lookupUser.js
Fixes https://github.com/hmcts/slack-help-bot/issues/410
Adds each AI response one at a time (skipping any that area empty)
e.g. user clicks next, then they see knowledge store results, next again shows previous tickets, next shows analytics information then create finishes the process
Lots of manual testing ensuring end 2 end flow works and variations where results don't have one or multiple results
> Add one page at a time

- app.js
- config/custom-environment-variables.yaml
- src/modules/appInsights.js
- src/slackHandlers/beginHelpRequest.js
- src/slackHandlers/showPlatoDialogue.js
- src/slackHandlers/startHelpForm.js
- src/slackHandlers/submitHelpRequest.js
- src/slackHandlers/submitInitialHelpRequest.js
Part of https://github.com/hmcts/slack-help-bot/issues/383
Store events as user navigates workflow for analytics.
Code is a bit complex as its trying to record events even when parts of it are skipped due to no results so that numbers are accurate for recording and analytics. 
Tested these scenarios manually:
- Knowledge store and related issues
- Related issues
- No related issues or knowledge store
All is displaying the right results
```
customEvents
| where name !contains "Test"
| summarize event_count = count() by bin(timestamp, 20m), name
| render columnchart 
```
> Record events as users navigate workflow

- README.md
- app.js
- src/modules/appInsights.js
- src/slackHandlers/appMention.js
- src/slackHandlers/reactionAdded.js
- src/slackHandlers/showPlatoDialogue.js
Fixes https://github.com/hmcts/slack-help-bot/issues/383
Capture events when use 👍 or 👎 thread summarising
Tested interactively:
> Collect feedback from thread summarising

- src/ai/prompts.js
- src/messages/helpFormData.js
See [DTSPO-18481](https://tools.hmcts.net/jira/browse/DTSPO-18481)
Lax sent me this info
> DTSPO-18481 Tweak crime fields

- app.js
- src/ai/prompts.js
- src/messages/helpFormData.js
- src/messages/helpRequestMain.js
- src/messages/helpRequestResolve.js
- src/slackHandlers/documentHelpRequest.js
- src/slackHandlers/resolveHelpRequest.js
- src/slackHandlers/startHelpRequestHandler.js
See [DTSPO-18481](https://tools.hmcts.net/jira/browse/DTSPO-18481)
Add in areas for crime and resolution fields
Add support for splitting resolution between crime and non crime
Add environment mappings for LLM I forgot to add in https://github.com/hmcts/slack-help-bot/pull/430
Interactivity tested raising both crime and non crime tests, full end 2 end and re-opened requests and resolved again (this did catch one issue but resolved now)
> [DTSPO-18481] - Add more crime fields

- components/infrastructure/ai-search-hmcts-way-indexer.tf
- components/infrastructure/ai-storage.tf
`│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPrincipalId" Message="The Principal ID '/servicePrincipals/29703cf0-15f5-411c-be38-425663df214b' is not valid. Principal ID must be a GUID."
│ 
│   with azurerm_role_assignment.search_contributor_hmcts_way,
│   on ai-search-hmcts-way-indexer.tf line 24, in resource "azurerm_role_assignment" "search_contributor_hmcts_way":
│   24: resource "azurerm_role_assignment" "search_contributor_hmcts_way" {
│ 
╵`
`╷
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPrincipalId" …
> Fix infra pipeline

- app.js
- Enables debug logs for slack help bot
- Trying to diagnose issue that is preventing some requests from being created
> Enable debug logs

- app.js
Reverts hmcts/slack-help-bot#485
> Revert "Enable debug logs"

- app.js
- Enables debug logs in slack help bot
- Was missing the import of `LogLevel` previously
> Enable Debug Logging

- app.js
Reverts hmcts/slack-help-bot#488
> Revert "Enable Debug Logging"

- src/messages/util.js
[DTSPO-22071](https://tools.hmcts.net/jira/browse/DTSPO-22071)
This part is the bug fix with a default value when a highlight cannot be generated.
Seeing this issue when multiple hmcts way documents are being suggested to the user (about  5). It also seems to commonly happen to the Environment Schedule one, potentially the schedule table is linked.
Tested locally multiple times, could replicate easily locally.
> Bug Fix for issues not submitting

- src/extractDocumentsForIndex.js
DTSPO-22168
Atlassian team are removing type 'BAU Task' - moving everything to 'Support'
> updated jira type

- src/messages/helpRequestResolve.js
Reverts hmcts/slack-help-bot#602
> Revert "Updating categories when resolving tickets"

- components/infrastructure/ai-services.tf
> Fix pipeline issues

- components/infrastructure/ai-services.tf
> Fix ai services issue

- components/infrastructure/ai-services.tf
> Resolving ai services issue

- src/messages/helpRequestResolve.js
> Update ticket resolution categories

- components/infrastructure/ai-hub.tf
- components/infrastructure/ai-model.tf
- components/infrastructure/ai-permissions.tf
- components/infrastructure/ai-project.tf
- components/infrastructure/ai-services.tf
- components/infrastructure/app-insights.tf
- components/infrastructure/provider.tf
See [DTSPO-26014](https://tools.hmcts.net/jira/browse/DTSPO-26014)
- Updates azurerm to 4.31.0
- Updates azapi to 2.4.0
- Removes most instances of azapi provider usage (See ticket for more info)
> Remove references to azapi where possible

- src/messages/helpRequestResolve.js
> Update resolution info URL link
